### ISSUE TITLE
chore: investigate deployment on gh pages or another alternative to Vercel

### ISSUE THREAD

**Issue by alice-ang** [GECO-Project-App/facilitation-app#15]

**Comment by alice-ang** [comment]
There seem to be alot of things that we use that are not supported if we deploy with static pages like github pages: https://nextjs.org/docs/app/building-your-application/deploying/static-exports#unsupported-features

**Comment by eliasfaltin** [comment]
We now have deployments live using coolify. Will have to test the ease of use over time of this (plus I need to try self-hosting supabase on it as well) before we commit to using this on the final vps we will get.
