### ISSUE TITLE
chore: translations

### ISSUE THREAD

**Issue by alice-ang** [GECO-Project-App/facilitation-app#28]
Create metadata for all pages and update swedish and english. Right now we only have to starter text 

{
  "page": {
    "title": "Project GECO",
    "desc": "Help team leaders establish and maintain productive group dynamics by becoming better facilitators"
  },
  "home": {
    "title": "Project GECO",
    "desc": "Help team leaders establish and maintain productive group dynamics by becoming better facilitators"
  }
}

**Comment by eliasfaltin** [comment]
Down the line, we would want to integrate a CMS or "non tech person" friendly way to edit and update texts across the app easily.
Furthermore, contributors should have an easy time updating and contributing to translations of the app in the future.
